#ifndef _WNCKMM_WRAP_INIT_H
#define _WNCKMM_WRAP_INIT_H

/** This file is part of wnckmm

    Copyright (c) 2013 Povilas Kanapickas  <povilas@radix.lt>

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with this library.  If not, see <http://www.gnu.org/licenses/>.
*/

// wrap_init.cc is generated by tools/generate_wrap_init.pl

namespace Wnck
{

void wrap_init();

} /* namespace Wnck */

#endif // _GDKMM_WRAP_INIT_H
